version: "3"

services:
  server:
    build:
      context: .
    ports:
      - "5000:5000"
      - "3000:3000"
    volumes:
      - ./server:/server
      - ./client:/client
    command: npm run dev